type Query {
	characters: [Character!]!
	character(id: ID!): Character
}

type Character {
	id: ID!
	name: String!
	actor: String!
	description: String!
	total_episodes: Int!
	photo: String!
	votes: Int!
	url: String!
}

type Mutation {
	addVote(character: ID!): Rs!
	updateVote(id: ID!, character: ID!): Rs!
	deleteVote(id: ID!): Rs!
}

type Subscription {
	changeVotes: [Character!]!
}

type Rs {
	status: Boolean!
	msg: String!
	characters: [Character!]!
}
